name: Run Tests

on:
  push:
    branches:
      - main  # or your default branch
  pull_request:
    branches:
      - main  # or your default branch

jobs:
  test:
    runs-on: ubuntu-latest  # You can also use windows-latest or macos-latest if needed

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Set your required Python version here

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Assuming your dependencies are listed in requirements.txt

    - name: Run tests
      run: |
        pytest  # This runs the tests
